// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrDf5-Xe7WxGDXgyef0vnEJfRPhNJ2o9o',
    appId: '1:977976551963:web:bce3b9b10deb3f1712a6be',
    messagingSenderId: '977976551963',
    projectId: 'journal-39d8d',
    authDomain: 'journal-39d8d.firebaseapp.com',
    storageBucket: 'journal-39d8d.appspot.com',
    measurementId: 'G-D5P6MKV7DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ9rw3Trc0Ip8EuJPCNXswNyMaJNQ4VCw',
    appId: '1:977976551963:android:2b37e6d15c8aaf4d12a6be',
    messagingSenderId: '977976551963',
    projectId: 'journal-39d8d',
    storageBucket: 'journal-39d8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT71UlCcfRAfgFdomCQTIqSLM6_bwrv0o',
    appId: '1:977976551963:ios:886ed988a4768cd312a6be',
    messagingSenderId: '977976551963',
    projectId: 'journal-39d8d',
    storageBucket: 'journal-39d8d.appspot.com',
    iosClientId: '977976551963-t66c8h0p24bdsvo3u94ef8vcc1cpqtgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.journal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT71UlCcfRAfgFdomCQTIqSLM6_bwrv0o',
    appId: '1:977976551963:ios:886ed988a4768cd312a6be',
    messagingSenderId: '977976551963',
    projectId: 'journal-39d8d',
    storageBucket: 'journal-39d8d.appspot.com',
    iosClientId: '977976551963-t66c8h0p24bdsvo3u94ef8vcc1cpqtgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.journal',
  );
}
